---

- name: Install app
  action: shell
          cd /var/www/ && curl {{ apppkg }} | tar xz;
          mv wordpress blog;
          cd blog
  sudo: yes

- name: Remove index.html
  file: path=/var/www/index.html state=absent
  sudo: yes

- name: Copy index.php
  template: src=index.php.j2 dest=/var/www/index.php owner=root group=root mode=0644
  sudo: yes

- name: Copy info.php
  template: src=info.php.j2 dest=/var/www/info.php owner=root group=root mode=0755
  sudo: yes

- name: Configure app
  template: src=wp-config.php.j2 dest=/var/www/blog/wp-config.php owner=root group=root mode=0644
  sudo: yes

- name: Remove old db entries in /etc/hosts
  lineinfile: |
      dest=/etc/hosts state=absent regexp='^.* owly.db.*$' backup=yes
  sudo: yes

- name: Add entries in /etc/hosts
  lineinfile: |
      dest=/etc/hosts state=present regexp='^.* owly.db.local*$' line="{{ dbhost }} {{ host }}" backup=yes
  sudo: yes

- name: Restart Apache
  service: name=apache2 state=restarted
  sudo: yes
