---

- apt: pkg={{item}} state=present update_cache=yes install_recommends=yes
  sudo: yes
  with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb


- name: Start the MySQL service
  action: service name=mysql state=started
  sudo: yes


- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ data['mysql']['pass'] }} priv=*.*:ALL,GRANT
  sudo: yes
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost


- name: Copy .my.cnf file with root password credentials
  template: src=root.my.cnf dest=/root/.my.cnf owner=root mode=0600
  sudo: yes


- name: Remove blank users
  mysql_user: name='' host={{ item }} state=absent
  sudo: yes
  with_items:
    - "{{ ansible_hostname }}"
    - localhost


- name: Remove test database
  mysql_db: name=test state=absent
  sudo: yes

- name: Change bind configs
  copy: src=bind.cnf dest=/etc/mysql/conf.d/bind.cnf owner=root group=root mode=644 backup=no
  sudo: yes
  notify: restart mysql

