- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ data['mysql']['pass'] }} priv=*.*:ALL,GRANT
  sudo: yes
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

