---

- name: Start the MySQL service
  action: service name=mysql state=started
  sudo: yes


- name: Create myapp database
  mysql_db: name={{ name }} state=present
  sudo: yes


- name: Create myapp user
  mysql_user: name={{ user }} host={{ item }} password={{ pass }} priv={{ name }}.*:ALL state=present
  with_items:
    - "{{ ansible_hostname }}"
    - localhost
    - "%"
  sudo: yes

