---
#tasks

- apt: pkg={{item}} state=present install_recommends=yes
  sudo: yes
  with_items:
    - libapache2-mod-php5
    - php5-curl
    - php5-cli
    - php5-cgi
    - php5-gmp
    - php5-gd
    - php5-mcrypt
    - php5-memcached
    - php5-mysql
  notify: restart apache
