---
# This playbook deploys the AWX application (database, web and worker) to a
# single server.

#- hosts: all
#  tasks:
#    - name: fetch host role types
#      group_by: key={{ ansible_local['system']['host']['role'] }}


- hosts: all
  user: ubuntu
  roles:
    - base

- hosts: tag_*_web
  user: ubuntu
  vars_files:
      #source vars/common
    - "../vars/common.yml"

      #source vars/{dev,stage,prod}/common vars
    - [ "../vars/{{ ansible_local['system']['host']['env'] }}/common.yml", "../vars/misc/common.yml" ]

      #source {dev,stage,prod}/{db,web}/common vars
    - [ "../vars/{{ ansible_local['system']['host']['env'] }}/roles/web/common.yml", "../vars/{{ ansible_local['system']['host']['env'] }}/roles/misc/common.yml" ]
  roles:
    - { role: base }
    - { role: web }
      # - { role: webapp, env={{ ansible_local['system']['host']['env'] }}  }
      # - { role: misc, env={{ ansible_local['system']['host']['env'] }}, role={{ ansible_local['system']['host']['role'] }}}


- hosts: tag_*_db
  user: ubuntu
  vars_files:
      #source vars/common
    - "../vars/common.yml"

      #source vars/{dev,stage,prod}/common vars
    - [ "../vars/{{ ansible_local['system']['host']['env'] }}/common.yml", "../vars/misc/common.yml" ]

      #source {dev,stage,prod}/{db,web}/common vars
    - [ "../vars/{{ ansible_local['system']['host']['env'] }}/roles/db/common.yml", "../vars/{{ ansible_local['system']['host']['env'] }}/roles/misc/common.yml" ]
  roles:
    - { role: base }
    - { role: db }
      # - { role: misc, env={{ ansible_local['system']['host']['env'] }}, role={{ ansible_local['system']['host']['role'] }}}
